---
title: "Assignment 1: Data Set Selection and Initial Processing"
author: "Luke Zhang"
output: html_document
---

Note: many code chunks were adapted from Prof. Isserlin's BCB420 lectures and Dr. Boris Steipe's online BCH441 modules.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download the Data Set

I chose GEO dataset [GSE83213](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE83213) for this assignment. First, install the required packages to download off of GEO.

```{r package, results='hide', message=FALSE}
if (! requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
if (! requireNamespace("GEOquery", quietly = TRUE)) {
    BiocManager::install("GEOquery")
}
```

Now download the supplementary files (only if they have not been downloaded already):
```{r download}
datafile <- "GSE83213_non-normalized.txt.gz"
if (!file.exists(datafile)) {
    files <- GEOquery::getGEOSuppFiles("GSE83213", makeDirectory = FALSE)
}
data <- read.delim(datafile,header=TRUE)
length(rownames(data))
colnames(data)
```

